"""OFFLINE codegen: bake per-finger PoE constants into constants.py.

NOT imported by the runtime solver (which must be pure / no I/O). Run this only
to regenerate src/finger_retarget/constants.py when the URDF changes:

    python -m src.finger_retarget.gen_constants

It uses the shared FK authority (``src/kinematics``) and the single convention
source (``src/kinematics.conventions``) to extract the zero-pose spatial joint
axes and segment geometry for the ADR-0003 (Finding-1) convention, and emits
Python literals. The runtime then needs no URDF, no yourdfpy, no file I/O.

Finding-1 distal constants (ADR-0006): the fingertip vector at tip command theta
is the exact closed form

    v(theta) = R(k, theta) . mvec0  +  R(k, (1+ratio).theta) . dvec0

with mvec0 = P_c - P_b (middle/proximal bone), dvec0 = fingertip0 - P_c (distal
bone), k the tip axis, ratio the DIP/IP mimic multiplier. We bake mvec0, dvec0,
ratio (plus the legacy unit rprox0/rdist0/ktip0 and base axes/limits).
"""
from __future__ import annotations

import os

import numpy as np

from src.kinematics.conventions import FINGERS, FINGER_ORDER, BASE_LINK
from src.kinematics.fk import L20FK

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _world_axis(urdf, base, jname):
    """Spatial axis of joint ``jname`` in the base frame at the current cfg."""
    j = urdf.joint_map[jname]
    R = urdf.get_transform(j.child, base)[:3, :3]
    return R @ np.asarray(j.axis, dtype=float)


def _unit(v):
    return v / np.linalg.norm(v)


def _tip_ratio(fk, spec):
    """The DIP/IP mimic multiplier whose driver is this finger's tip joint."""
    for mname, (driver, mult, off) in fk.mimics.items():
        if driver == spec.tip_joint:
            return float(mult)
    raise AssertionError(f"no mimic driven by {spec.tip_joint!r} found")


def build(side):
    fk = L20FK(side)
    urdf = fk._urdf
    base = BASE_LINK[side]
    fk.set_cfg({})  # zero pose

    def origin(link):
        return fk.link_origin(link)

    def limit(jn):
        return tuple(float(x) for x in fk.limits[jn])

    out = {}
    for name in FINGER_ORDER:
        spec = FINGERS[name]
        pa, pb, pc = origin(spec.link_a), origin(spec.link_b), origin(spec.link_c)
        ft = fk.fingertip(spec)             # zero-pose physical fingertip
        rprox0 = _unit(pb - pa)
        mvec0 = pc - pb                     # middle/proximal bone vector (m)
        dvec0 = ft - pc                     # distal bone vector (to fingertip)
        rdist0 = _unit(mvec0)              # legacy unit middle bone (kept)
        ktip0 = _world_axis(urdf, base, spec.tip_joint)
        ratio = _tip_ratio(fk, spec)

        # base axes + indices + limits, in CHAIN order outer->inner.
        if spec.is_thumb:  # thumb: yaw(opp) -> roll(abd) -> pitch(base)
            chain = [(spec.opp_idx, spec.opp_joint),
                     (spec.abd_idx, spec.abd_joint),
                     (spec.base_idx, spec.base_joint)]
        else:              # non-thumb: roll(abd) -> pitch(base)
            chain = [(spec.abd_idx, spec.abd_joint),
                     (spec.base_idx, spec.base_joint)]
        base_axes = [(idx, _world_axis(urdf, base, jn).tolist(), list(limit(jn)))
                     for idx, jn in chain]

        out[name] = dict(
            landmarks=list(spec.landmarks),
            base_idx=spec.base_idx, abd_idx=spec.abd_idx,
            tip_idx=spec.tip_idx, opp_idx=spec.opp_idx,
            is_thumb=spec.is_thumb,
            rprox0=rprox0.tolist(), rdist0=rdist0.tolist(),
            ktip0=ktip0.tolist(), tip_limit=list(limit(spec.tip_joint)),
            mvec0=mvec0.tolist(), dvec0=dvec0.tolist(), tip_ratio=ratio,
            base_axes=base_axes,  # [(idx, axis[3], (lo,hi)), ...] outer->inner
        )
    return out


def _fmt(x, p=10):
    if isinstance(x, float):
        return repr(round(x, p))
    if isinstance(x, list):
        return "[" + ", ".join(_fmt(v, p) for v in x) + "]"
    if isinstance(x, tuple):
        return "(" + ", ".join(_fmt(v, p) for v in x) + ")"
    return repr(x)


def emit():
    data = {side: build(side) for side in ("right", "left")}
    lines = [
        '"""AUTO-GENERATED by gen_constants.py — DO NOT EDIT BY HAND.',
        "",
        "Baked PoE constants for the closed-form L20 retargeting solver, per the",
        "ADR-0003 (Finding-1) segment convention. Regenerate with:",
        "    python -m src.finger_retarget.gen_constants",
        "",
        "Per finger/side: landmark indices, semantic joint indices, zero-pose unit",
        "segment directions (rprox0/rdist0), tip axis (ktip0) and limit, the distal",
        "fingertip-curve vectors (mvec0=P_c-P_b, dvec0=fingertip-P_c) and DIP/IP",
        "mimic ratio (tip_ratio), and the base-DoF spatial axes in chain order",
        "(outer->inner) with limits.",
        '"""',
        "",
        "ACTIVE_IDX = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 16, 17, 18, 19]",
        "RESERVED_IDX = [11, 12, 13, 14]",
        "N_JOINTS = 20",
        "FINGER_ORDER = ['thumb', 'index', 'middle', 'ring', 'little']",
        "",
        "CONSTANTS = {",
    ]
    for side, fingers in data.items():
        lines.append(f"    {side!r}: {{")
        for name, d in fingers.items():
            lines.append(f"        {name!r}: dict(")
            for k in ("landmarks", "base_idx", "abd_idx", "tip_idx", "opp_idx",
                      "is_thumb", "rprox0", "rdist0", "ktip0", "tip_limit",
                      "mvec0", "dvec0", "tip_ratio"):
                lines.append(f"            {k}={_fmt(d[k])},")
            lines.append("            base_axes=[")
            for (idx, axis, lim) in d["base_axes"]:
                lines.append(f"                ({idx}, {_fmt(axis)}, {_fmt(tuple(lim))}),")
            lines.append("            ],")
            lines.append("        ),")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "constants.py")
    with open(target, "w") as fh:
        fh.write(emit())
    print("wrote", target)
